# Generated by Django 5.1 on 2024-08-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='chair',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
