# Generated by Django 5.1 on 2024-08-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='destance',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
