# Generated by Django 5.1 on 2024-08-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_travel_destance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='orogin',
            new_name='origin',
        ),
    ]
