# Generated by Django 5.1 on 2024-08-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_orogin_travel_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='o_d',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destance',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
