# Generated by Django 5.1 on 2024-08-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_distance_o_d_alter_travel_destance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
