# Generated by Django 5.1 on 2024-08-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_travel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
