# Generated by Django 5.1 on 2024-08-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_travel_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='chair',
            field=models.SmallIntegerField(default=0),
        ),
    ]
