# Generated by Django 5.1 on 2024-08-27 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_travel_chair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='chair',
        ),
        migrations.AddField(
            model_name='travel',
            name='sell_chair',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
