# Generated by Django 5.1 on 2024-08-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_travel_sell_chair_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='sell_chair',
        ),
        migrations.AddField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
