# Generated by Django 5.1 on 2024-08-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_travel_sell_chair_ticket_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='sell_chair',
            field=models.SmallIntegerField(default=0),
        ),
    ]
