# Generated by Django 5.1 on 2024-08-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_travel_sell_chair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
