# Generated by Django 5.1 on 2024-08-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diver',
            field=models.BooleanField(default=False),
        ),
    ]
