# Generated by Django 5.1 on 2024-08-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_diver_user_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
