# Generated by Django 5.1 on 2024-08-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='origin',
        ),
        migrations.AddField(
            model_name='driver',
            name='National_code',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
